name: e2e full suite
on: pull_request
jobs:
  wait-for-calypso-live:
    name: Wait for Calypso.live
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, '[Status] Needs Review') || contains(github.event.pull_request.labels.*.name, '[Status] Needs e2e Testing') || contains(github.event.pull_request.labels.*.name, '[Status] Needs e2e Testing Gutenberg Edge') || contains(github.event.pull_request.labels.*.name, '[Status] Needs e2e Testing horizon')
    steps:
      - uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache yarn modules
        uses: actions/cache@v2
        env:
          cache-name: cache-yarn-modules
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: v{{ .Environment.GLOBAL_CACHE_PREFIX }}-yarn-modules-{{ checksum ".nvmrc" }}-{{ checksum "yarn.lock" }
          restore-keys: |
            v{{ .Environment.GLOBAL_CACHE_PREFIX }}-yarn-modules-{{ checksum ".nvmrc" }}-{{ checksum "yarn.lock" }}
            v{{ .Environment.GLOBAL_CACHE_PREFIX }}-yarn-modules-{{ checksum ".nvmrc" }}
      - name: Install yarn deps
        run: DETECT_CHROMEDRIVER_VERSION=true yarn install --frozen-lockfile
      - name: Check external author
        run: |
              if [[ ! -z $CIRCLE_PR_USERNAME ]]; then
                echo 'PRs from external authors cannot run on calypso.live'
                exit 1
              fi
      - name: Wait for calypso.live build
        if: github.event_name == 'pull_request' && ( github.event.action == 'labeled' || github.event.action == 'synchronize' )
        env:
          COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
        run: ./test/e2e/scripts/wait-for-running-branch.sh
  e2e-full-suite-desktop:
    name: e2e Full Suite - Desktop
    runs-on: ubuntu-latest
    needs: wait-for-calypso-live
    strategy:
      fail-fast: false
      matrix:
        ci_node_total: [4]
        ci_node_index: [0, 1, 2, 3]
    steps:
      - uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache yarn modules
        uses: actions/cache@v2
        env:
          cache-name: cache-yarn-modules
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: v{{ .Environment.GLOBAL_CACHE_PREFIX }}-yarn-modules-{{ checksum ".nvmrc" }}-{{ checksum "yarn.lock" }
          restore-keys: |
            v{{ .Environment.GLOBAL_CACHE_PREFIX }}-yarn-modules-{{ checksum ".nvmrc" }}-{{ checksum "yarn.lock" }}
            v{{ .Environment.GLOBAL_CACHE_PREFIX }}-yarn-modules-{{ checksum ".nvmrc" }}
      - name: Install yarn deps
        run: DETECT_CHROMEDRIVER_VERSION=true yarn install --frozen-lockfile
      - name: Decrypt Config
        env:
          NODE_CONFIG_ENV: test
          CONFIG_KEY: ${{ secrets.CONFIG_KEY }}
        run: cd test/e2e && npm run decryptconfig
      - name: Split Test files
        run: echo "::set-env name=TESTFILES::"$(npx mocha-split-tests -r ./runtime.log -f "specs*/**/*spec.js" -s "," -t ${{ matrix.ci_node_total }} -g ${{ matrix.ci_node_index }})""
      - name: Run Tests
        env:
          NODE_CONFIG_ENV: test
          BRANCHNAME: $GITHUB_REF
          TEST_VIDEO: true
        run: cd test/e2e && ./run.sh -R -g -s desktop -S ${{ github.event.pull_request.head.sha }} -f ${TESTFILES}
      - uses: actions/upload-artifact@master
        if: always()
        with:
          name: screenshots
          path: ./test/e2e/screenshots
  e2e-full-suite-mobile:
    name: e2e Full Suite - Mobile
    runs-on: ubuntu-latest
    needs: wait-for-calypso-live
    strategy:
      fail-fast: false
      matrix:
        ci_node_total: [4]
        ci_node_index: [0, 1, 2, 3]
    steps:
      - uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache yarn modules
        uses: actions/cache@v2
        env:
          cache-name: cache-yarn-modules
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: v{{ .Environment.GLOBAL_CACHE_PREFIX }}-yarn-modules-{{ checksum ".nvmrc" }}-{{ checksum "yarn.lock" }
          restore-keys: |
            v{{ .Environment.GLOBAL_CACHE_PREFIX }}-yarn-modules-{{ checksum ".nvmrc" }}-{{ checksum "yarn.lock" }}
            v{{ .Environment.GLOBAL_CACHE_PREFIX }}-yarn-modules-{{ checksum ".nvmrc" }}
      - name: Install yarn deps
        run: DETECT_CHROMEDRIVER_VERSION=true yarn install --frozen-lockfile
      - name: Decrypt Config
        env:
          NODE_CONFIG_ENV: test
          CONFIG_KEY: ${{ secrets.CONFIG_KEY }}
        run: cd test/e2e && npm run decryptconfig
      - name: Split Test files
        run: echo "::set-env name=TESTFILES::"$(npx mocha-split-tests -r ./runtime.log -f "specs*/**/*spec.js" -s "," -t ${{ matrix.ci_node_total }} -g ${{ matrix.ci_node_index }})""
      - name: Run Tests
        env:
          NODE_CONFIG_ENV: test
          BRANCHNAME: $GITHUB_REF
          TEST_VIDEO: true
        run: cd test/e2e && ./run.sh -R -g -s mobile -S ${{ github.event.pull_request.head.sha }} -f ${TESTFILES}
      - uses: actions/upload-artifact@master
        if: always()
        with:
          name: screenshots
          path: ./test/e2e/screenshots

